Uscart1 mostrar carret guests
UB-ES-2020/Alejandria pull request #142
Opened 2020-11-21 12:06 UTC by laurentiuNedelcu

Els usuaris que no s'hagin loguejat tindran un carret per posar els seus productes. Si surt de la web i torna a entrar seguirà veient els productes que ha afegit anteriorment.
Quan aquest usuari es registra, es crea un carret amb els productes que hagi afegit al carret (si no ha afegit cap producte es crea un carret buit).
Si un usuari (registrat) no està loguejat i ha afegit productes al carret, quan es logueja els productes que ha afegit s'afegeixen juntament als altres. Si ha afegit 1 producte que ja tenia, no es torna a posar (1 quantitat del producte determinat).
Les funcions afegir i eliminar funcionen correctament.

2020-11-22 13:57 UTC, ojimenmu requested changes
These changes look good to me.
Can you add the issue this pull request is closing with: Closes #<<number_issue>>

2020-11-23 10:28 UTC, ojimenmu requested changes
As Oscar already pointed out, we get the following error:
```
Internal Server Error: /
Traceback (most recent call last):
  File "/home/m00rphy/Desktop/venv/ES_python38/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/m00rphy/Desktop/venv/ES_python38/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/m00rphy/Desktop/venv/ES_python38/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/m00rphy/Desktop/venv/ES_python38/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/m00rphy/Desktop/venv/ES_python38/lib/python3.8/site-packages/django/views/generic/list.py", line 157, in get
    context = self.get_context_data()
  File "/media/data/Data/_UB/7s/_ES/Projecte/Alejandria/books/views.py", line 103, in get_context_data
    device = self.request.COOKIES['device']
KeyError: 'device'

```

2020-11-23 11:41 UTC, laurentiuNedelcu commented
Bug resolved: la cookie no estava creada quan s'inicialitzava per primera vegada el carret.

2020-11-23 15:06 UTC, OscarFernandezBatalla approved these changes
Approved!

2020-11-23 15:18 UTC, ojimenmu approved these changes
Tested and functional. All good.

2020-11-23 20:40 UTC, bernatosoriogomez approved these changes
Tot okey

2020-11-23 21:53 UTC, merged